name: cyano-annotation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # System tools
  - circos
  - perl
  
  # Python runtime
  - python=3.10
  
  # Install the package itself in editable mode with pip
  - pip
  - pip:
      - -e .  # Installs cyano-annotation from pyproject.toml